### ISSUE TITLE
Notification drop down

### ISSUE THREAD

**Issue by clamster25** [PoomSmart/EmojiPort-Legacy#6]
Date size is much smaller and out of place in Notification Center

**Comment by clamster25** [comment]
![image](https://cloud.githubusercontent.com/assets/1207019/7396751/b877df04-ee71-11e4-8ce3-be714f6b7814.jpg)

**Comment by Starshooter1996** [comment]
That must be caused by a different tweak I do not have that issue

**Comment by Starshooter1996** [comment]
To figure out what tweak could be causing the issue is to have Icleaner and disable emoji83 and see if that is the issue itself, if the problem still persists it's a different tweak. If it goes away then it must be for the iPhone your on. Because I'm on an iPhone 5S upscaled to 6 and I have no issues like that.

**Comment by PoomSmart** [comment]
Recently this problem was gone.
